### ISSUE TITLE
remove a sensor 

### ISSUE THREAD

**Issue by richardmoizeau** [openmsupply/msupply-cold-chain#103]
be able to disconnect/unpair/remove a sensor from a tablet (sensor is malfunctioning, sensor is needed in another cold storage...)

**Comment by Chris-Petty** [comment]
@joshxg As said elsewhere, you can't add a sensor back after removing it. Says it succeeds but then it doesn't move from found list to available list, doesn't show in sensor chart list. 

Unclear in this, but should we delete the sensor's history too? Probably not 'cause we'll want it sync. Better to leave dormant.

But, if adding the same sensor back on, then what? I think start a new history, but up for discussion!

**Comment by Chris-Petty** [comment]
I'll have that discussion!

If I have a fridge with a sensor that gets destroyed, I'd actually want to replace that sensor and have the chart/logs continue (and display the gap in data). Would introduce the concept of locations into this app, though (I think that's a good thing, but not trivial!)

**Comment by joshxg** [comment]
Yes I went with a soft delete because sync system, easier (maybe), history and things like that.

The intention was that if you reconnect a sensor it will just create a new sensor record and history. Went with this for now though it is arguable that we could match on macAddress and 'continue' logging.

I think the easiest solution is to just pretend nothing happened and start fresh. If we do want to match history on say, a dashboard, then we can match sensors on macaddress in sql quite easily.

re locations: We can link sensors to locations in mSupply (one day) and then we can show all logs for a location, rather than a sensor in (my opinon) more appropriate interfaces (grafana and desktops for proper analysis).

I suppose a set of goals/aims for the app would be good to help in making decisions like this (i.e. maybe it is a simpleish way to monitor a fridge with limited history or maybe it is a full monitoring solution with complex analytics!)

**Comment by Chris-Petty** [comment]
Tested, fixed in 0.0.3-rc9.

Adding/removing/Adding the same sensor works 👍
