### ISSUE TITLE
add sensor name to csv export to avoid overwriting

### ISSUE THREAD

**Issue by richardmoizeau** [openmsupply/msupply-cold-chain#104]
downloading temp logs to your computer (not sending via email): if done within the same minutes, second download will overwrite the 1st one because same file name, ex: 23-04-2021-1121, DD-MM-YYYY-HHMM)

add sensor name as in: Sensorname_23-04-2021-1121

**Comment by richardmoizeau** [comment]
@joshxg, high priority, May 10th, don't hurt me.

**Comment by Chris-Petty** [comment]
Tested, fixed in 0.0.3-rc9.

@joshxg as messaged, one caveat is that sensors added in 0.0.2 that weren't given a name, once on 0.0.3-rc9 the exports use `null` as their name (so this problem still actually occurs). Would be good to migrate sensor.macAddress to sensor.name if they don't have a name yet.

Further out issue, might be good to check that names are unique when editing them.
