### ISSUE TITLE
Replace a sensor

### ISSUE THREAD

**Issue by Chris-Petty** [openmsupply/msupply-cold-chain#115]
**Is your feature request related to a problem? Please describe.**
I have a sensor configured. It breaks. I must replace it. I want to replace it and have its logs continue off from where the last one died.

**Describe the solution you'd like**
I'd like a button where I can replace a sensor. 

**Describe alternatives you've considered**
Just removing the sensor and having the logs start fresh. I don't think it's good because the continuity of logs _for the fridge_ is important.

**Additional context**
Related to #103

**Comment by joshxg** [comment]
Given the app has no context of what a fridge/location is I am not sure how to implement this.

I think this is essentially replacing the mac address of a sensor? In that case, are we not ruining the continuity of what logs were created from a particular sensor? (We don't have historic context of when the sensor was changed).

I'm sure theres some sort of use case with maintenance etc.

We can remove the sensor and then add a new one, replacing the sensor on desktop to the location. This use case is surely the more likely, given the dashboards will be reporting on long running temperatures for locations, rather than using the app?

**Comment by Chris-Petty** [comment]
I'm not tracking what's going on with the desktop side of the apps integration, but I agree that this isn't much doable in app without introducing locations to the schema.

The process currently (please correct me if wrong):

1. Be on site, diagnose sensor is bork
2. In app press button to remove the sensor
3. Add a new sensor, perhaps with the same name as the old one
4. Go to mSupply desktop
5. Disassociate the old sensor from the location
6. Associate the new sensor with the location

The idea with this issue would be to achieve:

1. Be on site, diagnose sensor is bork
2. In app press button to replace sensor, select new sensor
3. (Everything else is magic, don't have to access mSupply Desktop it's syncing with)

I'd imagine this would be particularly useful for users who are mobile in the field and are syncing the app with a central server, they may otherwise have limited access to rejig mSupply. Either that or they make support tickets every time they need to replace a sensor.

**Comment by joshxg** [comment]
Yes, with the additional steps we get to preserve the history for which log was recorded for which sensor. It's quite easy to implement this feature if that use case isn't wanted

**Comment by Chris-Petty** [comment]
Closing 'cause we agree that it's bit of an edge case. Sensors should break very frequently. If you have a faulty one you will probably find out when initially setting it up at which point you'd remove it from the app and replace it immediately (and it won't have been configured on mSupply desktop to relate to a location yet).

Implementing locations would be a massive change with heaps of complexity. Doing the mac address change loses tracking of "which sensor recorded what logs". Dunno if we want that. Leave it till there is a clear need for easier sensor replacement!
