### ISSUE TITLE
Sensor initial temperature/breach UI in wrong state

### ISSUE THREAD

**Issue by Chris-Petty** [openmsupply/msupply-cold-chain#121]
**Describe the bug**

Sometime when setting up a sensor, it'll show a weird state of low battery/cold breach, then gradually come right.

![Screenshot_2021-05-11-19-38-31-857](https://user-images.githubusercontent.com/7684221/117777640-e9a6f580-b290-11eb-9ca9-bbb087d74d3a.jpeg)
![Screenshot_2021-05-11-19-39-18-056](https://user-images.githubusercontent.com/7684221/117777657-ed3a7c80-b290-11eb-8b9e-a51cf1125495.jpeg)
![image](https://user-images.githubusercontent.com/7684221/117777604-df84f700-b290-11eb-9194-30b403e72a25.png)

**To Reproduce**

Not sure how reliable this is going to be to reproduce, I've had it twice with same sensor, wiped app data and repeated. Only tried on the one particular sensor, probably unlikely but could be the sensor being weird.

1. Set default logging interval to 1min (likely unnecessary step)
2. Add 1 sensor
3. Add a 2nd sensor
4. Before they've logged anything change the second sensor name
5. Wait for logs to come in
6. (bug, 1st pic) See UI state show 2nd sensor as having low battery and blue breach (clicking on breach takes you to the acknowledge modal)
7. Click on sensor detail, go back. Battery state says 100% but still got cold/low battery breach state. (2nd pic)
8. Wait for sync and another refresh. UI goes back to normal. (3rd pic)

**Expected behavior**
The sensor state doesn't bork.

**Smartphone (please complete the following information):**
 - Device: lenovo tab 10 TB-X304L
 - OS: Android 8.1
 - Version: 0.0.3-rc4

**Additional context**

Arrangement of UI elements seems wrong as well, maybe low battery alert needs testing/work? (Assuming that's a thing)

**Comment by Chris-Petty** [comment]
Exists on 0.0.3-rc7. Needed restart to get battery % to update (still showed a battery-cold-breach). Several syncs later state came right.

![image](https://user-images.githubusercontent.com/7684221/118342707-98408400-b578-11eb-92d8-a8ec37be57cf.png)

![Screenshot_2021-05-15-12-26-58-960](https://user-images.githubusercontent.com/7684221/118342765-f66d6700-b578-11eb-813f-41e68dc16f25.jpeg)

![Screenshot_2021-05-15-12-38-56-619](https://user-images.githubusercontent.com/7684221/118343052-b0190780-b57a-11eb-8468-c4da02748f8c.jpeg)

**Comment by joshxg** [comment]
Are you saying it is showing a state of cold breach because it is blue?

Without seeing a cold breach icon, it looks as if the sensor is in a low battery state. It's likely in a low battery state because the default is a low value rather than a `null` value as we haven't read the temperature, yet.

There is an operation that runs every so often which will read the battery state and update it in the background.

1. Fix the default battery level to be a `null` value rather than a `low value` so we can display something like `n/a` rather than the incorrect 'low'
2. Fix the default danger zone colour to be red (?) instead of blue because that is evidently confusing.
3. Read the battery level of a sensor having been connected with earlier than the background scheduled operation - i.e. when we connect with it

Will do 1 and 2 as they should be a little easier. 3 will take a bit more time and testing so will be done later.

**Comment by joshxg** [comment]
Have ended up doing all 3 and released a new release candidate rc-9

**Comment by Chris-Petty** [comment]
Tested, fixed in 0.0.3-rc9. Magic??
