### ISSUE TITLE
Failing to download logs

### ISSUE THREAD

**Issue by Chris-Petty** [openmsupply/msupply-cold-chain#143]
**Describe the bug**

Cannot download logs, gives screen/dialog:

![image](https://user-images.githubusercontent.com/7684221/119279766-e7c23680-bc81-11eb-9561-0b8bbe26c2d3.png)

Upgrading tablets with this issue seems to have changed the behaviour slightly. Stays on this for ages:

![image](https://user-images.githubusercontent.com/7684221/119754554-cd43c380-bef4-11eb-9b90-1b5dd41fa534.png)

**To Reproduce**

Not sure how to replicate sorry! Might sensors that came from upgrade code from 0.0.2 to 0.1.1, as the customer using them have had this issue since upgrading- waiting to hear if it's affecting all the tablets upgraded.

1. Look at sensor detail
2. Click download button
3. Provide name etc.
4. Press OK
5. See error

**Expected behavior**
Downloads as expected. Normally says in a bottom toast "Report written to [path]".

**Smartphone (please complete the following information):**
 - Device: Lenovo tablet (newer model)
 - OS: ?
 - Version 0.1.1

**Additional context**

**Comment by joshxg** [comment]
I haven't been able to recreate this (exactly) on master. However I was able to recreate it on and older version.

I believe the `null` fix was fixed here: https://github.com/openmsupply/msupply-cold-chain/commit/3bc9d58068935281e56844461635f0d54d7328f7#diff-9387a4d991af3efe28052f632a9e1e6b4a4ebe01bf399537865a2f6d401970ddR243

The error messages do need to be improved.

Additionally it would be better if a user has more control over the logs which are downloaded.

This was to fullfil the WHO requirement - if I remember correctly it was something about being able to download data into a microsoft excel-able format.. so I whipped this up for the WHO spec lab to download the logs.

At the moment it queries for all of the logs, ever, and tries to write them. I imagine the UX when there are several 10's or 100's of 1000's of logs might be less then ideal!

**Comment by joshxg** [comment]
### Quick investigation findings

So I have found that there is exponential growth in the time to write a report. Specifically in parsing the json into csv. When exceeding about ~30k logs it essentially is useless.

We can fix this by chunking up the logs and parsing smaller amounts at a time, but at some point this becomes useless also as we're only cutting the problem down by a linear factor.

### Generic solution

So, essentially the current method of creating the report has to change to support writing bigger reports. Specifically we would need to change the current, quickly thrown together method of:

1. start creating report
2. query for data for a section of the report
3. turn data into csv
4. concat csv into variable
5. Go to step 2 and repeat until all sections are complete
6. try to write csv to disk

into something far more robust:

1. Start creating report
2. Start creating section of the report
3. query for subset of data for a section of the report
4. turn data into csv
5. write csv to file
6. Go to step 3 and repeat until no more subsets remain
7. Go to step 2 and repeat until no more sections remain

### Other thoughts

- Additionally there is the issue for https://github.com/openmsupply/msupply-cold-chain/issues/99 - exporting data for all sensors at once. This would add an additional loop to loop over each sensor.
- This is going to take a decent amount of time to generate the report on the tablet especially after a few months of 1 minute log intervals. It would be better if there was a date range picker.

With these two thoughts, I thought an optimal solution might be to create a wizard or just a normal page in the settings, rather than the current implementation. I.e - go to settings, there is a list item for `Reporting`, when you go there you can select which sensors you want to export for, then you can select the date range, the comment field, username etc. 

Additionally, once users are seeing the logs on desktop [and can create dashboards and better reports in desktop] I wonder how often users will actually use this feature.

So, *if* the best solution is completely changing how we do reports, but the feature might actually not be used very frequently, I think it would be best to do a quicker solution until the feature is validated by customers and there is a real need to enhance the feature more?

### Proposed suggestion

- Use the date range filters to create the report.
- Show the date range in the modal which appears
- If the number of logs exceeds 50k, give a warning to the user and just take the most recent 50,000 logs. [reasoning: this is a lot of logs- more than a month of 1 minute interval logs. I claim there likely isn't a real use case for creating a csv report for more than a months worth of logs in one go on the tablet and if there is, the cost is not worthwhile to support it]
- Change the code to chunk the logs such that writing 50k logs is sufficiently fast
- Close https://github.com/openmsupply/msupply-cold-chain/issues/99 for now

**Comment by Chris-Petty** [comment]
Yes

**Comment by ArpitaSussol** [comment]
Tested in 0.4.1-rc2

### Testing

- [x] Look at sensor detail
- [x] Click download button
- [x] Provide name etc.
- [x] Press OK
- [x] No error. Log file is downloading
