### ISSUE TITLE
EPIC: mSupply integration

### ISSUE THREAD

**Issue by joshxg** [openmsupply/msupply-cold-chain#19]
We need to send all the data from the app to msupply and/or other servers

**Comment by wlthomson** [comment]
A rough flowchart of what the sync workflow could look like:

![cce_sync](https://user-images.githubusercontent.com/43223637/113475189-87f4ae00-94d0-11eb-948b-1fba44b8c3d9.png)

**Comment by joshxg** [comment]
Looks good to me!

Could you clarify the cookie storage concept for me? It implies to me database storing but could mean a bunch of different stuff so just wanna stay on the same page

**Comment by wlthomson** [comment]
> Could you clarify the cookie storage concept for me? It implies to me database storing but could mean a bunch of different stuff so just wanna stay on the same page

ATM, my thinking is to store the cookie in the redux store (no need for persisting it longer than the duration of the session), but open to other suggestions!

**Comment by joshxg** [comment]
Ah yup- I think it's a minor implementation detail that doesn't matter- just not able to see the flow of the cookie being used in the store, as in my mind the usage would only be for the life of the method which was pushing the data- but I guess if you're dispatching different actions to do different stuff? I dunno, will see I guess 😁

**Comment by wlthomson** [comment]
Hm, I think not storing the cookie would be fine, and I see what you mean by it not being necessary. 

One reason I can think of for storing the token is that it is more flexible in terms of recovering from errors, as not storing the token requires performing all the HTTP requests "atomically" for one sync operation (e.g. every time a push fails, you need to get a new token to resume sync). This might be relevant for some of our users in areas where connectivity is unreliable/intermittent? I could also see an argument for storing the token as being a bit more future proof, e.g. if we add an expiry to the token so that login isn't required every time data is pushed.

**Comment by wlthomson** [comment]
More of an epic than an individual issue so will resolve when feature branch https://github.com/openmsupply/msupply-cold-chain/tree/msupply-integration is merged.

**Comment by joshxg** [comment]
Should be ready for testing now
