### ISSUE TITLE
Reassement: V1 UI

### ISSUE THREAD

**Issue by josh-griffin** [openmsupply/msupply-cold-chain#4]
Placeholder issue: A list of all current UI implementations for MVP, which should be re-assessed for V1.

**Comment by joshxg** [comment]
# Not finished

### General
- Tab bar
    - Icons
    - General shape/feel
    - Tab navigation: animation
- Device Status
    - Battery
    - Anything else?

### Sensor List View
- No data state
- Charts
    - Location of X axis
    - X Axis ticks/domain
    - Y Axis ticks/domain
    - Gradient
    - Size on list view
- Status
    - Size of font of temperature when NORMAL v DANGER
    - Battery
    - Last synced
    - Could show: Next sync? Last failed? Currently syncing (flashing)?
- General
    - Divider
- Cumulative breach
    - How to display

### Sensor Detail View
In general: Need to clarify what we are doing on this page more clearly - i.e. with breaches?
- Chart
    - As above
- Sensor Status
    - Show? What temperature?
- Name
- Table
    - need clarification on colours to use
    - Need to clarify what columns
    - Pagination over infinite scroll?
- "Button" Row (The row currently where selecting a date and exporting data buttons are).
    - Any other buttons needed?
    - If that's all we have, need a nicer design
- Date range picker
    - Need to somehow add times - can add into modal popup?

**Comment by GaryWilletts** [comment]
@joshxg The tab indicator at the bottom of the screen is a bit counter-intuitive and always made me think the wrong tab was active - outlined in red in this screenshot:

![CCE app UI](https://user-images.githubusercontent.com/11517184/105150243-6a808c80-5afc-11eb-97b7-73dea408d689.png)

The problem is that the tab that isn't active has the same background colour as the background of the active tab. That makes it look like it's the Settings tab that is active, when in fact it's the Sensors tab.

In my humble opinion, in this screenshot the background colours of the tabs should be swapped. Would also be good if the white line separating the tab indicator from the tab could be removed over the top of the active tab's indicator and was instead a white line around the left, right and bottom edges of the tab indicator - like in this screenshot:

![CCE app UI tabs](https://user-images.githubusercontent.com/11517184/105150321-897f1e80-5afc-11eb-9aae-db4c30e64f9d.png)

This is what it would look like when the Settings tab is active but with the Sensors text greyed out not the Settings - my image manipulation skills only go so far 😉. Maybe looks better without a right hand edge line...

**Comment by adamdewey** [comment]
We've moved on...
